# Import the shared state structure used by all LangGraph agents
from app.agents.state import AgentState 

# Import the function that returns the configured LLM(via Portkey gateway)
from app.gateway import get_langchain_llm

# Import Logfire for logging and tracing execution
import logfire

# Get an LLM configured for the planner agent
# Uses Portkey with caching, retries, and fallback internally
llm = get_langchain_llm(feature="planner")

# Planner Node
# Planner node receives the current workflow state
def planner_node(state: AgentState):
    """
    Determines whether the user's query requires document retrieval or can be answered directly from the conversational history.
    """
    # Initialize an empty string to store previous conversation
    history = ""

    # Iterate through all previous messages except the latest one
    for msg in state["messages"][:-1]:
        # Determine whether the sender was the User or Assistant
        role = "User" if msg["role"] == "user" else "Assistant"

        # Append the message to the conversational history
        history += f"{role}: {msg['content']}\n"

    # Extract the latest user message
    # If no message exist, use an empty string
    user_message = (
        state["messages"][-1]["content"]
        if state["messages"]
        else ""
    )

    # Create the prompt that will be sent to the LLM
    prompt = f"""
    You are an intelligent Assitant Planner.
    Analyze the conversation history and the latest user message. 

    CONVERSATION HISTORY:
    {history} 

    LATEST MESSAGE:
    "{user_message}" 

    Task:
    1. If the latest message is a greeting (hi, hello) or a question that can be answered using ONLY the conversational history above (e.g., "what is my name"), respond with 'CONVERSATIONAL'.
    2. If it is a technical question about Kubernetes, Intel, or Networking that requires fresh documentation, output a refined search query.ConnectionAbortedError
    Output ONLY 'CONVERSATIONAL' or the search query. 
    """

    # Start a Logfire tracing span for the planner
    with logfire.span("Planner Decision"):

        # Send the prompt to the LLM and remove extra whitespaces
        decision = llm.invoke(prompt).content.strip() 

        # Log the planner's decision
        logfire.info(f"Intent identified: {decision}")

    # If the planner decides retrieval is NOT required
    if decision == "CONVERSATIONAL":

        # Return updated workflow state
        return {
            # Indicate conversation handling
            "current_query": "CONVERSATIONAL",
            # Update current workflow status
            "status": "Handling conversationally (using memory)...",
            # Store execution plan for debugging/monitoring
            "plan": [
                "Intent: Conversational/Memory",
                "Retrieval: Skipped"
            ]
        }
    # Otherwise retrieval is required
    return {
        # Store the refined search query generated by the planner
        "current_query": decision,

        # Update workflow status
        "status": (
            f"Technical research needed. "
            f"Searching for: {decision}"
        ),
        # Store execution plan
        "plan": [
            "Intent: Technical",
            f"Search Term: {decision}"
        ]
    }